services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: npm install && mkdir -p bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp && chmod +x bin/yt-dlp
    startCommand: export PATH=$PATH:$PWD/bin && npm start
    envVars:
      - key: NODE_ENV
        value: production

